# Generated by Django 6.0.3 on 2026-03-20 11:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_options_room_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='room',
            name='rooms_room_price_a62835_idx',
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
