# Generated by Django 6.0.3 on 2026-03-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('date_start',)},
        ),
    ]
