# Generated by Django 6.0.3 on 2026-03-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('date_start', 'id')},
        ),
    ]
